In [54]:
import pandas as pd
import json
import numpy as np
import sqlite3

df = pd.read_csv(r"D:\RW\RW_Exam\Data_Preprocecing\Exam\Data\riders - riders.csv.csv")

with open("Data/trips.json", "r") as file:
    metadata = json.load(file)

conn = sqlite3.connect("city_zones.db")
with open(r"D:\RW\RW_Exam\Data_Preprocecing\Exam\Data\city_zones.sql", "r", encoding="utf-8") as file:
    sql_script = file.read()
conn.executescript(sql_script)
zones_df = pd.read_sql("SELECT * FROM city_zones", conn)

display(zones_df.head())
print(zones_df.info())
print(zones_df.isnull().sum())
print(zones_df.describe())


metadata_df = pd.DataFrame(metadata)
display(metadata_df.head())
print(metadata_df.info())
print(metadata_df.isnull().sum())
print(metadata_df.describe())

display(df.head())
print(df.info())
print(df.isnull().sum())
print(df.describe())

print("Duplicate rows:", df.duplicated().sum())
print("Invalid age entries:", df[df['age'] < 10].shape[0])

  zone_name  population_density  traffic_index  avg_speed_kmph    zone_type
0    Zone_1                4921           2.43            30.9  Residential
1    Zone_2                6371           0.91            58.4  Residential
2    Zone_3               12971           2.11            38.0     Business
3    Zone_4                4038           2.46            48.2     Business
4    Zone_5                2590           1.31            43.9     Business

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   zone_name           10 non-null     object
 1   population_density  10 non-null     int64
 2   traffic_index       10 non-null     float64
 3   avg_speed_kmph      10 non-null     float64
 4   zone_type           10 non-null     object
dtypes: float64(2), int64(1), object(2)
memory usage: 532.0+ bytes
None
zone_name             0
population_density    0
traffic_index         0
avg_speed_kmph        0
zone_type             0
dtype: int64
       population_density  traffic_index  avg_speed_kmph
count           10.000000      10.000000       10.000000
mean          7458.100000       1.570000       42.470000
std           4527.581706       0.703199        9.666557
min           2440.000000       0.540000       30.900000
25%           4157.500000       1.010000       35.950000
50%           5646.000000       1.685000       40.950000
75%          11061.750000       2.065000       47.450000
max          14627.000000       2.460000       58.400000

,trip_id,rider_id,zone,distance_km,duration_min,fare_amount,payment_mode,ride_date,surge_flag
0,T00001,R0037,Zone_10,11.83,74.59,104.88,Cash,2023-11-13,0
1,T00002,R0104,Zone_9,3.86,35.59,40.48,Cash,2023-07-28,1
2,T00003,R0045,Zone_8,4.70,31.03,46.39,Cash,2024-01-14,1
3,T00004,R0089,Zone_2,11.06,59.48,257.64,Cash,2023-12-13,0
4,T00005,R0003,Zone_5,7.28,67.59,72.74,UPI,2023-03-15,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trip_id       2000 non-null   object
 1   rider_id      2000 non-null   object
 2   zone          2000 non-null   object
 3   distance_km   2000 non-null   float64
 4   duration_min  2000 non-null   float64
 5   fare_amount   2000 non-null   float64
 6   payment_mode  2000 non-null   object
 7   ride_date     2000 non-null   object
 8   surge_flag    2000 non-null   int64
dtypes: float64(3), int64(1), object(5)
memory usage: 140.8+ KB
None
trip_id         0
rider_id        0
zone            0
distance_km     0
duration_min    0
fare_amount     0
payment_mode    0
ride_date       0
surge_flag      0
dtype: int64
       distance_km  duration_min  fare_amount   surge_flag
count  2000.000000   2000.000000  2000.000000  2000.000000
mean      8.247420     61.883410   134.600375     0.510500
std       4.450904     35.980603    85.521989     0.500015
min       0.020000      0.190000     0.250000     0.000000
25%       4.887500     35.415000    70.440000     0.000000
50%       8.115000     58.950000   121.850000     1.000000
75%      11.362500     85.375000   182.867500     1.000000
max      25.860000    201.070000   472.290000     1.000000

,rider_id,name,age,gender,city,signup_date,total_rides,cancelled_rides,avg_rating
0,R0001,Aarav Das,23,Male,Pune,2020-06-29,56,0,3.76
1,R0002,Ishaan Nair,39,Female,Mumbai,2019-11-23,70,5,4.12
2,R0003,Kavya Reddy,34,Male,Pune,2023-05-04,45,9,3.76
3,R0004,Aarav Nair,19,Other,Kolkata,2019-07-28,464,5,3.19
4,R0005,Diya Reddy,27,Male,Ahmedabad,2021-05-31,294,30,3.53

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rider_id         300 non-null    object
 1   name             300 non-null    object
 2   age              300 non-null    int64
 3   gender           300 non-null    object
 4   city             300 non-null    object
 5   signup_date      300 non-null    object
 6   total_rides      300 non-null    int64
 7   cancelled_rides  300 non-null    int64
 8   avg_rating       300 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 21.2+ KB
None
rider_id           0
name               0
age                0
gender             0
city               0
signup_date        0
total_rides        0
cancelled_rides    0
avg_rating         0
dtype: int64
              age  total_rides  cancelled_rides  avg_rating
count  300.000000   300.000000       300.000000  300.000000
mean    31.466667   244.690000        22.983333    3.991000
std      7.863098   146.406843        21.455633    0.559643
min     18.000000     4.000000         0.000000    3.000000
25%     26.000000   112.750000         7.000000    3.547500
50%     31.000000   241.000000        16.000000    3.925000
75%     37.000000   366.750000        32.000000    4.480000
max     55.000000   499.000000        94.000000    5.000000
Duplicate rows: 0
Invalid age entries: 0

2

In [55]:
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

#1. Handle numeric missing values using SimpleImputer (mean)
numeric_cols = metadata_df.select_dtypes(include='number').columns
num_imputer = SimpleImputer(strategy='mean')
metadata_df[numeric_cols] = num_imputer.fit_transform(metadata_df[numeric_cols])

#2. Handle categorical missing values using SimpleImputer (most frequent)
categorical_cols = metadata_df.select_dtypes(include='object').columns
cat_imputer = SimpleImputer(strategy='most_frequent')
metadata_df[categorical_cols] = cat_imputer.fit_transform(metadata_df[categorical_cols])

#3.Use KNN Imputer for multivariate columns.
knn_cols = ['duration_min', 'distance_km', 'fare_amount']
knn_imputer = KNNImputer(n_neighbors=5)
metadata_df[knn_cols] = knn_imputer.fit_transform(metadata_df[knn_cols])

In [56]:
# 4. Convert date columns to datetime format
metadata_df['ride_date'] = pd.to_datetime(metadata_df['ride_date'])
df['signup_date'] = pd.to_datetime(df['signup_date'])

In [57]:
# 5.Remove Unrealistic values
metadata_df = metadata_df[metadata_df['fare_amount'] >= 0]

metadata_df = metadata_df[
    ~((metadata_df['distance_km'] == 0) & 
      (metadata_df['fare_amount'] > 0))
]

3.

In [58]:
from scipy.stats import zscore
from scipy.stats.mstats import winsorize

before = metadata_df[['fare_amount', 'distance_km', 'duration_min']].agg(['mean', 'std', 'min', 'max'])

print("BEFORE:")
print(before)

BEFORE:
      fare_amount  distance_km  duration_min
mean   134.600375     8.247420     61.883410
std     85.521989     4.450904     35.980603
min      0.250000     0.020000      0.190000
max    472.290000    25.860000    201.070000

In [59]:
from scipy.stats import zscore
from scipy.stats.mstats import winsorize

# Z-score detection
fare_z = zscore(metadata_df['fare_amount'])
distance_z = zscore(metadata_df['distance_km'])

fare_anomalies = metadata_df[abs(fare_z) > 3]
distance_anomalies = metadata_df[abs(distance_z) > 3]

print("Fare anomalies:", len(fare_anomalies))
print("Distance anomalies:", len(distance_anomalies))


# IQR for duration
Q1 = metadata_df['duration_min'].quantile(0.25)
Q3 = metadata_df['duration_min'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

duration_anomalies = metadata_df[
    (metadata_df['duration_min'] < lower) |
    (metadata_df['duration_min'] > upper)
]

print("Duration anomalies:", len(duration_anomalies))


# Winsorization
metadata_df['fare_amount'] = winsorize(
    metadata_df['fare_amount'],
    limits=[0.01, 0.01]
)

Fare anomalies: 16
Distance anomalies: 3
Duration anomalies: 18

In [60]:
after = metadata_df[['fare_amount', 'distance_km', 'duration_min']].agg(['mean', 'std', 'min', 'max'])

print("\nAFTER:")
print(after)

comparison = pd.concat([before, after],keys=['Before', 'After'])

print("\nBEFORE VS AFTER:")
print(comparison)

AFTER:
      fare_amount  distance_km  duration_min
mean   134.225030     8.247420     61.883410
std     84.221107     4.450904     35.980603
min      3.270000     0.020000      0.190000
max    379.630000    25.860000    201.070000

BEFORE VS AFTER:
             fare_amount  distance_km  duration_min
Before mean   134.600375     8.247420     61.883410
       std     85.521989     4.450904     35.980603
       min      0.250000     0.020000      0.190000
       max    472.290000    25.860000    201.070000
After  mean   134.225030     8.247420     61.883410
       std     84.221107     4.450904     35.980603
       min      3.270000     0.020000      0.190000
       max    379.630000    25.860000    201.070000

4

In [66]:
# 1. Convert datetime → hour, day_of_week, month

metadata_df['ride_date'] = pd.to_datetime(metadata_df['ride_date'])

metadata_df['hour'] = metadata_df['ride_date'].dt.hour
metadata_df['day_of_week'] = metadata_df['ride_date'].dt.dayofweek
metadata_df['month'] = metadata_df['ride_date'].dt.month


# 2. Encode categorical columns

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['gender'] = label_encoder.fit_transform(df['gender'])


# Merge zone data

metadata_df = metadata_df.merge(
    zones_df,
    left_on='zone',
    right_on='zone_name',
    how='left'
)


# 3. Create traffic level from traffic index

metadata_df['traffic_level'] = pd.qcut(
    metadata_df['traffic_index'],
    q=3,
    labels=['Low', 'Medium', 'High']
)


# 4. Ordinal Encode traffic level

from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder(
    categories=[['Low', 'Medium', 'High']]
)

metadata_df['traffic_level'] = ordinal_encoder.fit_transform(
    metadata_df[['traffic_level']]
)


# 5. One-Hot Encode payment mode and zone

metadata_df = pd.get_dummies(
    metadata_df,
    columns=['payment_mode', 'zone'],
    drop_first=False
)


# 6. Log transform on fare and distance

import numpy as np

metadata_df['fare_log'] = np.log1p(
    metadata_df['fare_amount']
)

metadata_df['distance_log'] = np.log1p(
    metadata_df['distance_km']
)


# 7. Square-root transform on duration

metadata_df['duration_sqrt'] = np.sqrt(
    metadata_df['duration_min']
)


# Check final result

print(metadata_df.head())
print(metadata_df.shape)

KeyError: 'zone'