In [2]:
import pandas as pd
import numpy as np

data = {
    'Age':    [22,  np.nan, 25,  23,  np.nan, 21,  24,  np.nan],
    'Income': [30000, np.nan, 45000, np.nan, 28000, np.nan, 52000, np.nan],
}

data = pd.DataFrame(data)

In [3]:
data["Age_missing"] = data["Age"].isnull().astype(int)
data["Income_missing"] = data["Income"].isnull().astype(int)

In [4]:
data.head()

    Age   Income  Age_missing  Income_missing
0  22.0  30000.0            0               0
1   NaN      NaN            1               1
2  25.0  45000.0            0               0
3  23.0      NaN            0               1
4   NaN  28000.0            1               0

In [5]:
random_sample = data['Age'].dropna().sample(data['Age'].isna().sum(), random_state=42)
random_sample.index = data[data['Age'].isna()].index
data.loc[data['Age'].isna(), 'Age'] = random_sample

print(data)

    Age   Income  Age_missing  Income_missing
0  22.0  30000.0            0               0
1  25.0      NaN            1               1
2  25.0  45000.0            0               0
3  23.0      NaN            0               1
4  24.0  28000.0            1               0
5  21.0      NaN            0               1
6  24.0  52000.0            0               0
7  23.0      NaN            1               1

# KNN impute

In [6]:
from sklearn.impute import KNNImputer

In [ ]:
data = {
    'Rider':           ['Raju', 'Suresh', 'Amit', 'Vikram', 'Pooja',
                        'Kiran', 'Deepak', 'Meena', 'Arjun', 'Sunita'],
    'Deliveries_Day':  [18,   25,      np.nan, 30,      15,
                        22,   28,      np.nan, 19,      26     ],
    'Exp_Years':       [3,    5,       4,      6,       np.nan,
                        4,    5,       3,      np.nan,  5      ],
    'Avg_Distance_km': [8.5,  12.0,    10.5,   np.nan,  7.0,
                        9.5,  np.nan,  8.0,    9.0,     11.5   ],
    'Rating':          [4.2,  4.7,     np.nan, 4.9,     4.0,
                        4.4,  4.8,     4.1,    np.nan,  4.6    ],
}
data = pd.DataFrame(data)
display(data)

    Rider  Deliveries_Day  Exp_Years  Avg_Distance_km  Rating
0    Raju            18.0        3.0              8.5     4.2
1  Suresh            25.0        5.0             12.0     4.7
2    Amit             NaN        4.0             10.5     NaN
3  Vikram            30.0        6.0              NaN     4.9
4   Pooja            15.0        NaN              7.0     4.0
5   Kiran            22.0        4.0              9.5     4.4
6  Deepak            28.0        5.0              NaN     4.8
7   Meena             NaN        3.0              8.0     4.1
8   Arjun            19.0        NaN              9.0     NaN
9  Sunita            26.0        5.0             11.5     4.6

In [18]:
print(data.isnull().sum())

Rider              0
Deliveries_Day     2
Exp_Years          2
Avg_Distance_km    2
Rating             2
dtype: int64

In [22]:
KNN_imputer = KNNImputer(n_neighbors=2,weights='distance')
data_imputed = KNN_imputer.fit_transform(data[['Deliveries_Day', 'Exp_Years', 'Avg_Distance_km', 'Rating']])

data_imputed_df = pd.DataFrame(data_imputed, columns=['Deliveries_Day', 'Exp_Years', 'Avg_Distance_km', 'Rating'])
data_imputed_df.head()

   Deliveries_Day  Exp_Years  Avg_Distance_km    Rating
0       18.000000        3.0         8.500000  4.200000
1       25.000000        5.0        12.000000  4.700000
2       24.485281        4.0        10.500000  4.565685
3       30.000000        6.0         9.308233  4.900000
4       15.000000        3.0         7.000000  4.000000