In [28]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
data = pd.read_csv('Titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
print(data.isna().sum())
updated = data.drop('Age', axis=1)
updated = updated.drop('Cabin', axis=1)
updated.head()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,S

In [26]:
simple_imputer = SimpleImputer(strategy='most_frequent')
updated[['Embarked']] = simple_imputer.fit_transform(updated[['Embarked']])
print(updated.isna().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [31]:
data = {
    "Age": [25, np.nan, 35, 40, np.nan],
    "Salary": [3000, 4000, np.nan, 5000, 6000]
}
df = pd.DataFrame(data)
simple_imputer = SimpleImputer(strategy='mean')
df[['Age', 'Salary']] = simple_imputer.fit_transform(df[['Age', 'Salary']])
print(df)

df2 = pd.DataFrame(data=data)
simple_imputer = SimpleImputer(strategy='median')
df2[['Age', 'Salary']] = simple_imputer.fit_transform(df2[['Age', 'Salary']])
print(df2)

         Age  Salary
0  25.000000  3000.0
1  33.333333  4000.0
2  35.000000  4500.0
3  40.000000  5000.0
4  33.333333  6000.0
    Age  Salary
0  25.0  3000.0
1  35.0  4000.0
2  35.0  4500.0
3  40.0  5000.0
4  35.0  6000.0

In [35]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Gender": ["F", np.nan, "M", "M", np.nan],
    "City": ["New York", "Los Angeles", np.nan, "Chicago", "New York"]
}
df = pd.DataFrame(data)
print(df)
print("\n")
imputer_mode = SimpleImputer(strategy="most_frequent")
df_mode = df.copy()
df_mode[["Gender", "City"]] = imputer_mode.fit_transform(df[["Gender", "City"]])
print(df_mode)

print("\n")
imputer_const = SimpleImputer(strategy="constant", fill_value="Unknown")
df_const = df.copy()
df_const[["Gender", "City"]] = imputer_const.fit_transform(df[["Gender", "City"]])
print(df_const)

      Name Gender         City
0    Alice      F     New York
1      Bob    NaN  Los Angeles
2  Charlie      M          NaN
3    David      M      Chicago
4      Eva    NaN     New York


      Name Gender         City
0    Alice      F     New York
1      Bob      M  Los Angeles
2  Charlie      M     New York
3    David      M      Chicago
4      Eva      M     New York


      Name   Gender         City
0    Alice        F     New York
1      Bob  Unknown  Los Angeles
2  Charlie        M      Unknown
3    David        M      Chicago
4      Eva  Unknown     New York